# Generated by Django 2.0.2 on 2019-01-30 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightNumber', models.CharField(max_length=10)),
                ('registration', models.CharField(max_length=20)),
                ('aircraftType', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight_Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing', models.CharField(max_length=20)),
                ('arrivalTime', models.TimeField()),
                ('departureTime', models.TimeField()),
                ('cargoIn', models.IntegerField()),
                ('cargoOut', models.IntegerField()),
                ('mailIn', models.IntegerField()),
                ('mailOut', models.IntegerField()),
                ('PaxIn', models.IntegerField()),
                ('PaxOut', models.IntegerField()),
                ('pad', models.IntegerField()),
                ('asu', models.IntegerField()),
                ('gpu', models.IntegerField()),
                ('toiletBowser', models.IntegerField()),
                ('pau', models.IntegerField()),
                ('waterCart', models.IntegerField()),
                ('flightNumber', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opsdata.Flight_Detail')),
            ],
        ),
    ]
