# Generated by Django 2.0.2 on 2019-06-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_flightmovement_performance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightmovement',
            name='flightNumber',
        ),
        migrations.DeleteModel(
            name='Flightdetail',
        ),
        migrations.DeleteModel(
            name='Flightmovement',
        ),
    ]
