# Generated by Django 2.0.2 on 2019-06-13 11:32

from django.db import migrations, models
import django.db.models.deletion
import operations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0003_auto_20190613_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RiskDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_no', models.CharField(blank=True, default=operations.models.report_number, max_length=500, null=True)),
                ('station', models.CharField(choices=[('Harare', 'Harare'), ('Victoria Falls', 'Victoria Falls'), ('Bulawayo', 'Bulawayo'), ('Kariba', 'Kariba'), ('Other', 'Other')], default=0, max_length=20)),
                ('location_of_incident', models.CharField(max_length=100)),
                ('date_of_incident', models.DateField()),
                ('time_of_incident', models.TimeField()),
                ('incident_detail', models.TextField(max_length=3000)),
                ('likelyhood', models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1)),
                ('severity', models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1)),
                ('proposed_mitigation', models.TextField(max_length=3000)),
                ('reporter_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_required', models.TextField(max_length=3000)),
                ('resources_required', models.TextField(max_length=3000)),
                ('Action_Taken', models.TextField(blank=True, max_length=3000, null=True)),
                ('status', models.IntegerField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default=1)),
                ('reopen', models.BooleanField()),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignment', to='operations.Officials')),
                ('report_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.RiskDetail')),
                ('responsible_official', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsible_official', to='operations.Officials')),
            ],
        ),
    ]
