# Generated by Django 2.0.2 on 2019-09-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20190620_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskevaluation',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default=1, max_length=6),
        ),
    ]
