# Generated by Django 2.0.2 on 2019-09-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20190903_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskdetail',
            name='approval',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default=1, max_length=20),
        ),
    ]
