# Generated by Django 2.0.2 on 2019-09-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_riskdetail_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskdetail',
            name='hazard_category',
            field=models.CharField(choices=[('Aircraft hazard', 'Aircraft hazard'), ('Personal Injury', 'Personal Injury'), ('Equipment hazard', 'Equipment hazard'), ('Environmental hazard', 'Environmental hazard'), ('personal & equipment hazard', 'Personal & equipment hazard')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskdetail',
            name='hazard_type',
            field=models.CharField(choices=[('Aircraft Related', 'Aircraft Related'), ('Non Aircraft', 'Non Aircraft')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
