# Generated by Django 2.0.2 on 2019-09-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20190917_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskevaluation',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='riskevaluation',
            name='report_number',
        ),
        migrations.RemoveField(
            model_name='riskevaluation',
            name='responsible_official',
        ),
        migrations.AddField(
            model_name='riskdetail',
            name='Action_Taken',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='riskdetail',
            name='action_required',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskdetail',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignment', to='operations.Officials'),
        ),
        migrations.AddField(
            model_name='riskdetail',
            name='evidence_of_closure',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='riskdetail',
            name='reopen',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskdetail',
            name='resources_required',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskdetail',
            name='responsible_official',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsible_official', to='operations.Officials'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskdetail',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default=1, max_length=6),
        ),
        migrations.AlterField(
            model_name='riskdetail',
            name='approval',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='RiskEvaluation',
        ),
    ]
