# Generated by Django 2.0.2 on 2019-09-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_auto_20190928_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskdetail',
            name='approval',
        ),
    ]
