# Generated by Django 2.0.2 on 2019-09-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_auto_20190929_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskdetail',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed')], default=1, max_length=6, null=True),
        ),
    ]
