# Generated by Django 2.0.2 on 2019-10-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_auto_20191001_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskdetail',
            name='station',
            field=models.CharField(blank=True, choices=[('Harare', 'Harare'), ('Victoria Falls', 'Victoria Falls'), ('Bulawayo', 'Bulawayo'), ('Kariba', 'Kariba'), ('Other', 'Other')], default='Harare', max_length=20, null=True),
        ),
    ]
