# Generated by Django 2.0.2 on 2019-10-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_auto_20191010_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskdetail',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
