# Generated by Django 2.0.2 on 2019-10-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_riskdetail_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskdetail',
            name='residual_likelyhood',
            field=models.IntegerField(blank=True, choices=[(1, 'Extremely Improbable'), (2, 'Improbable'), (3, 'Remote'), (4, 'Occasional'), (5, 'Frequent')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='riskdetail',
            name='residual_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskdetail',
            name='residual_severity',
            field=models.IntegerField(blank=True, choices=[(1, 'Extremely Improbable'), (2, 'Improbable'), (3, 'Remote'), (4, 'Occasional'), (5, 'Frequent')], default=1, null=True),
        ),
    ]
