# Generated by Django 2.0.2 on 2019-10-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_auto_20191019_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskdetail',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Closed', 'Closed')], default=' ', max_length=10, null=True),
        ),
    ]
