# Generated by Django 2.0.2 on 2019-10-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_auto_20191019_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskdetail',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='riskdetail',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Closed', 'Closed')], default='Pending', max_length=10, null=True),
        ),
    ]
