# Generated by Django 2.0.2 on 2019-10-20 17:03

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('operations', '0023_auto_20191020_1855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
    ]
