# Generated by Django 2.0.2 on 2019-10-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_auto_20191023_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskdetail',
            name='active_status',
        ),
        migrations.AddField(
            model_name='riskdetail',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
