# Generated by Django 2.0.2 on 2019-10-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0026_auto_20191023_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskdetail',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
