# Generated by Django 2.0.2 on 2018-08-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainer_surname',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
