# Generated by Django 2.0.2 on 2018-08-27 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_remove_trainer_trainer_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='manager_app.Trainer'),
            preserve_default=False,
        ),
    ]
