# Generated by Django 2.0.2 on 2018-09-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_auto_20180827_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='archive',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
