# Generated by Django 2.0.2 on 2018-09-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0006_trainingrecord_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='mandatory',
            field=models.ManyToManyField(blank=True, null=True, to='manager_app.Course'),
        ),
    ]
