# Generated by Django 2.0.2 on 2018-10-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0008_auto_20180927_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtitle',
            name='mandatory',
        ),
        migrations.AddField(
            model_name='employee',
            name='mandatory_courses',
            field=models.ManyToManyField(to='manager_app.Course'),
        ),
    ]
